### ISSUE TITLE
Component 'as' prop not working as expected

### ISSUE THREAD

**Issue by aappoalander** [vrk-kpa/suomifi-ui-components#157]
'as' prop does not work as expected when used with e.g. Heading component. Component styles are not applied to the rendered component.

Tested with a NoteBox component in suomifi-design-system repo the following way:
<Heading.h3 as='h2'>{title}</Heading.h3>
When built with Gatsby the heading styles are not applied.

blocking #155

**Comment by J-Kallunki** [comment]
Okey so our typescript syntax is using components (from our own source) for `styled`-template literal. `as`-prop is feat in styled-components to change that `element` so it is changing our used component to example. `h2`-tag.

I will fix internally so that `as`-prop works for every component - where it is internally implemented: given to last child-component using styled with html-element not component.
